# Generated by Django 2.1.5 on 2022-05-23 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='registered_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2022, 5, 23)),
            preserve_default=False,
        ),
    ]
