# Generated by Django 2.1.5 on 2022-05-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientApp', '0002_patient_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=5),
        ),
    ]
