# Generated by Django 2.1.5 on 2022-05-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Receptionist'), (2, 'Doctor'), (3, 'Patient')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(to='UserApp.Roles'),
        ),
    ]
