# Generated by Django 2.1.5 on 2022-05-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Receptionist'), (2, 'Doctor'), (3, 'Patient')], default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
