# Generated by Django 2.1.5 on 2022-05-22 11:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from UserApp.models import User


class Migration(migrations.Migration):

    aadhar  = User.objects.get(username="123456789123")
    doc = User.objects.get(username="D16")
    dependencies = [
        ('UserApp', '0005_auto_20220522_1106'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='appointment',
            name='doc_id',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='doc_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='isApprovedByDoctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='isApprovedByReceptionist',
            field=models.BooleanField(default=False),
        ),
    ]
