# Generated by Django 2.1.5 on 2022-05-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_auto_20220522_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doc_id',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
