# Generated by Django 2.1.5 on 2022-05-22 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_auto_20220522_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('isApprovedByDoctor', models.BooleanField(default=False)),
                ('isApprovedByReceptionist', models.BooleanField(default=False)),
                ('aadhar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aadhar', to=settings.AUTH_USER_MODEL)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
