# Generated by Django 2.1.5 on 2022-05-23 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=15)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Appointment')),
            ],
        ),
    ]
