# Generated by Django 2.1.5 on 2022-06-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0004_diseases'),
        ('UserApp', '0012_notification_noti_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DoctorApp.Diseases'),
        ),
    ]
