# Generated by Django 2.1.5 on 2022-05-22 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.TextField()),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=1)),
                ('fees', models.IntegerField()),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('exp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='special_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DoctorApp.Specialities'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
