# Generated by Django 2.1.5 on 2022-06-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0003_auto_20220523_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('special_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorApp.Specialities')),
            ],
        ),
    ]
